### ISSUE TITLE
my interface with gfortran segfualts

### ISSUE THREAD

**Issue by krober10nd** [ivan-pi/fmetis#3]
Hello, 

Firstly, I'd like to thank you for the great work. I've had machine dependent problems with doing this call before. 

I'm using your interface in my F90 code but not able to get past the MeshToNodal call. 

All my variables are interoparable c types including the parameters to the call. The most important ones look like this:

 INTEGER(C_INT),POINTER :: NXADJ(:)=>null(),NADJNCY(:)=>null() ! nodal graph CRS structure 
  TYPE(C_PTR)            :: PTRNXADJ,PTRNADJNCY !args for metis 

I call the routine like this:

       ios=METIS_MeshToNodal(neT,npT,EPTR,EIND
      &  ,numflag,PTRNXADJ,PTRNADJNCY)
 
       if (ios /= METIS_OK) then
         write(*,*) "METIS_MeshToNodal failed with error: ", ios
         error stop 1
       end if
 
       CALL C_F_POINTER(PTRNXADJ,NXADJ,shape=[npT+1])
       CALL C_F_POINTER(PTRNADJNCY,NADJNCY,shape=[NXADJ(npT+1)-1])

and this works with Ifort but does not work with Gfortran.

I get the following message on the call to MeshToNodal

   Current memory used:           0 bytes
   Maximum memory used:           0 bytes
***Memory allocation failed for CreateGraphNodal: nptr. Requested size: 1420087986928848 bytes
 METIS_MeshToNodal failed with error:           -3
ERROR STOP 1

The mesh is triangular and I'm using the fortran numbering. I suspect it has something to do with the null() assignment but I'm not quite sure. 

Any help would be appreciated! Thanks

**Comment by ivan-pi** [comment]
Glad to hear the interface is useful. I have gotten a similar bug report from another user. Which version of gfortran and METIS are you using? In [this thread](http://glaros.dtc.umn.edu/gkhome/node/1171) on the METIS forum a user speculates it might be something to do with the default integer lengths.

The explicit initialization to null() is simply a good practice. If not explicitly initialized gfortran issues a warning -Wmaybe-uninitialized. The -3 error flag indicates that METIS returned due to insufficient memory. 

Can you confirm the nodal graph you recover is correct when you compile using `ifort`? One idea might be to verify your elemental  (eptr, eind) and nodal graphs (nxadj, nadjncy) are consistent using the METIS graph check command line tool (section 4 of the [manual](http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/manual.pdf)):
```
graphck graphfile [fixedfile]
```
A word of caution: for the C to Fortran pointer assignment in lines
```Fortran
CALL C_F_POINTER(PTRNXADJ,NXADJ,shape=[npT+1])
CALL C_F_POINTER(PTRNADJNCY,NADJNCY,shape=[NXADJ(npT+1)-1])
```
your graph should be provided using Fortran numbering or `numflag=1`.

**Comment by krober10nd** [comment]
Hey Ivan,

I'm using gfortran 9.1.0. I'm calling your wrapper from a subroutine from within a module in a F90 syntax. 

My flags for compilation are simply -O0 and -g. Interestingly, I can run the simple test case you provide with the same flags (removing the -std=f2018 and -wall and -march=native). 

However, when I paste the simple test case inside the subroutine, it still stalls out inside the call.

**Comment by ivan-pi** [comment]
Well the fact the problems are machine dependent is most likely linked to the default integer length. To quote an answer from [this thread](https://stackoverflow.com/questions/14515874/difference-between-int32-int-int32-t-int8-and-int8-t):

> Plain int is quite a bit different from the others. Where int8_t and int32_t each have a specified size, int can be any size >= 16 bits. At different times, both 16 bits and 32 bits have been reasonably common (and for a 64-bit implementation, it should probably be 64 bits).

 Are you using a precompiled METIS library? METIS can be compiled with either 32 or 64 bit integers ("idx_t").

The `integer(c_int)` I used throughout the wrapper turns out to be machine dependent. [This thread](https://stackoverflow.com/questions/44059466/what-is-the-need-for-a-c-int-fortran-type-are-c-and-fortran-integers-so-differe) was also enlightening. If your METIS library is 64-bit a possible fix could be to add the compiler flag -fdefault-integer-8.

I suppose the better way would be to declare an `idx_t` kind parameter
```Fortran
use iso_c_binding
integer, parameter :: idx_t = c_int32_t  ! or c_int64_t
```
and then replace the `integer(c_int)` with `integer(idx_t)` throughout the whole Fortran wrapper, just like in the METIS code. The same can be done for doubles. Of course caution is necessary also in the calling code.

**Comment by krober10nd** [comment]
Hey Ivan, 

Thanks, you helped me figure this out! I replaced C_INT with idx_t where idx_t is

integer, parameter :: idx_t = c_int32_t  ! or c_int64_t

and it through my blockage. I also updated the metis_interface.f90 wrapper with the idx_t for the KIND  Perhaps I can submit a pull request for this feature or do you want to do it? 

I also think it would be helpful if you made the METIS_INCLUDE and METIS_LIB paths more readily accessible to modify in the CMake gui (and not hardwired). Newer users to cmake may not find it easy to modify them in CMakeLists.txt and this created my problem in the first place. But this is just a light suggestion.

The installation of metis that I had on my computer had a definition of an INT that was 64 bits, which conflicted with the definition of an integer in Fortran. Furthermore, I had a rogue metis.h lying in my ParMETIS include directory, which further mucked things up. But that was my fault but that may be how ParMETIS builds (need to check that).

What a pain this bug (spent 3 days on this after work!) was but it from now on, I'm using the standard KIND definition.

**Comment by ivan-pi** [comment]
I'd be more than happy if you submit a pull request.

About the hardwired CMake include and lib folders, I am only a CMake beginner myself. I've seen some CMake modules online to automatically find METIS, which would be another improvement possible improvement.

According to the ParMETIS documentation, it ships with it's own copy of METIS.
